# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Create the package
        run: dotnet pack -c Release --output nupkgs
      - name: List File
        run: ls ./nupkgs
      - name: Publish
        run: dotnet nuget push "./nupkgs/*.nupkg" --skip-duplicate -k ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
    
